### PR TITLE
Implement automatic colour updates with GitHub Actions

### PR DESCRIPTION
**Pull request by pxeger**

### CODE REVIEW

**Comment by pxeger** [comment]
Sorry for the spam, anyone who's receiving it. Don't worry - I am too...

**Comment by pxeger** [comment]
It now works! Is this ok, @ozh? Currently I just have to run a script whenever I remember to, which is not a great solution.

> Never spend 6 minutes doing something by hand when you can spend 6 hours failing to automate it

**Comment by ozh** [comment]
Seems nice! I'm surprised there's no need for an action to setup ptyhon itself ?

**Comment by pxeger** [comment]
Nope, the GitHub Actions runners have the most common development environments pre-installed.

**Pull request merged**
