### PR TITLE
Changed The json structure of the color.json

### LINKED ISSUE #8: Change in Structure of the color.json
It will be great to change the structure of the color.json because till now it contains the a large number of the JSON Object in a single JSON Object . We should be changing  the structure so that it contains a JSON Array of the JSON Objects as all the Objects provided in the file  have same characteristics. Thus the JSON Object will easily serialize into JAVA objects by the Library Like GSON and Jackson.

### PR DESCRIPTION
**Pull request by RamolaWeb**
Fix #8 I Have Modified the structure of the color.json by creating a JSON Array of the Object of the Language having their url and color. Their is changes in the README.md and color.json to show the result of the change in the code.

### CODE REVIEW

**Comment by RamolaWeb** [comment]
@ozh  The Example of New JSON Structure is as follow :-
"GitHubColor": [
        {
            "1C Enterprise": {
                "color": "#814CCC", 
                "url": "https://github.com/trending?l=1C Enterprise"
            }
        }, 
        {
            "ABAP": {
                "color": "#E8274B", 
                "url": "https://github.com/trending?l=ABAP"
            }
        }]

**Comment by ozh** [comment]
So, just another level of nesting? I didn't understand how it makes things easier to parse

**Comment by RamolaWeb** [comment]
@ozh It will be good to have a collection of the Similar JSON objects  in the JSON Array

**Comment by elifoster** [comment]
What is the point of the "GitHubColor" key? The json could just be an array at top level.

**Pull request closed without merging**
