### PR TITLE
add HelloWorld repo as submodule ^^

### PR DESCRIPTION
**Pull request by g1f1**
The **g1f1/HelloWorld** repository is a list of Hello World programs in many programming languages.

### CODE REVIEW

**Comment by rk0cc** [comment]
I don't think the owner accepted your pull request since he crawls GitHub programming language colour already.

**Review by g1f1 — COMMENTED** [review]
These files add the [HelloWorld](https://github.com/g1f1/HelloWorld) repository to your repository.

**Comment by g1f1** [comment]
@rk0cc The [g1f1/HelloWorld](https://github.com/g1f1/HelloWorld) repository is a list of Hello World programs in many programming languages.. 
It has nothing to do with colors. Contains executable files that print HelloWorld. For this reason the owner may decide not to add it, I understand.

**Comment by thecaralice** [comment]
Honestly, I don't see *any* reason for the owner to merge this.

**Comment by ozh** [comment]
This is indeed out of scope. Neat repo anyway. There are already quite a few lists available, check for instance http://helloworldcollection.de/

**Comment by Ruzie** [comment]
> The **g1f1/HelloWorld** repository is a list of Hello World programs in many programming languages.

This more like an advertisement on issue page lol

**Comment by rk0cc** [comment]
> > The **g1f1/HelloWorld** repository is a list of Hello World programs in many programming languages.
> 
> This more like an advertisement on issue page lol

I think he is making destruction more than advertising as his reply for me:

>> @rk0cc The [g1f1/HelloWorld](https://github.com/g1f1/HelloWorld) repository is a list of Hello World programs in many programming languages.. 
>> It has nothing to do with colors. Contains executable files that print HelloWorld. For this reason the owner may decide not to add it, I understand.

I pointed that his PR is off-topic but he still think his PR is right.

**Pull request closed without merging**
